kind: Deployment
apiVersion: apps/v1
metadata:
  name: fotoshow
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fotoshow
  template:
    metadata:
      labels:
        app: fotoshow
    spec:
      containers:
        - name: fotoshow
          image: 'image-registry.openshift-image-registry.svc:5000/sam-sam-showcase/fotoshow@sha256:3353cb84e8a956a5c53f88da2e45153d465b4b7115ff28e80a4c4c4053305c89'
          ports:
            - containerPort: 18181
              protocol: TCP
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
