apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-prod

resources:
  - ../../base

images:
  - name: ghcr.io/inholland-cloud-minor-2526/group1-videoservice
    digest: sha256:43a264cf1469e5180a616d5da2ea55ada864d579e265b3a842fc9a800081180d
