apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-prod

resources:
- ../../base

images:
- digest: sha256:e7aa60f6ca5d47d26157ee16195f6af8ea087876a8d56413318ef6957809ab29
  name: ghcr.io/coendv/group1-chatservice
  newName: ghcr.io/coendv/group1-chatservice
- name: ghcr.io/coendv/group1-communityservice
  newTag: main
- name: ghcr.io/coendv/group1-notificationservice
  newTag: main
- name: ghcr.io/coendv/group1-recommendationservice
  newTag: main
- digest: sha256:8e1eacf1766d5dae6bfed4217ddf6c7e92a1343c5cebd90d979b39657f13fbe7
  name: ghcr.io/coendv/group1-userservice
  newName: ghcr.io/coendv/group1-userservice
- digest: sha256:14f2107ec0fd4f020743972fc5614a19c12748d992702266e001e0a95b79b5c6
  name: ghcr.io/coendv/group1-videoservice
  newName: ghcr.io/coendv/group1-videoservice
