apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-prod

resources:
- ../../base

patches:
- path: ../../base/UserService/patch-keycloak-hostname-prod.yaml
  target:
    kind: Deployment
    name: userservice-keycloak

images:
- digest: sha256:5f93fe8a655c5b22ff456c4b3f6964b79bb12d425c7dedc69e7bb0283e60ef5c
  name: ghcr.io/coendv/group1-chatservice
  newName: ghcr.io/coendv/group1-chatservice
- digest: sha256:4c59918fdb93cb45a56a8c7108114b0b6905a60da91ec40bb4001f97b4102267
  name: ghcr.io/coendv/group1-communityservice
  newName: ghcr.io/coendv/group1-communityservice
- digest: sha256:f60e3a62d1a49fa5c2352603d13e635162082325b443f8e5445fe1e9b96ffc06
  name: ghcr.io/coendv/group1-notificationservice
  newName: ghcr.io/coendv/group1-notificationservice
- digest: sha256:6d4de0a5e22413df8507487daf1922f793812fd90bc0235d58934982dfbfe691
  name: ghcr.io/coendv/group1-recommendationservice
  newName: ghcr.io/coendv/group1-recommendationservice
- digest: sha256:df68691a144729206ccb7197afe28c2788ff7d7b752fa04eedc3f7671c8764e7
  name: ghcr.io/coendv/group1-userservice
  newName: ghcr.io/coendv/group1-userservice
- digest: sha256:c09be7bf3e5f3390f1ac5a41824f2dcd649d31aaafb14c7ba50ba7260ecdc960
  name: ghcr.io/coendv/group1-videoservice
  newName: ghcr.io/coendv/group1-videoservice
