apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-prod

resources:
- ../../base

patches:
- path: ../../base/UserService/patch-keycloak-hostname-prod.yaml
  target:
    kind: Deployment
    name: userservice-keycloak

images:
- digest: sha256:cef64613cac003b6f20bc9cf2d8521633b46802fdc0e9e9c68fdd0823eac9675
  name: ghcr.io/coendv/group1-chatservice
  newName: ghcr.io/coendv/group1-chatservice
- digest: sha256:d9351e2b47ee0f1e4ad5d3bfb00f2203aa8697e92f3c19c17aa8c932f67975f1
  name: ghcr.io/coendv/group1-communityservice
  newName: ghcr.io/coendv/group1-communityservice
- digest: sha256:44f5848bd5fa015dc9270946442b17817e145f65c0e369fb998beacd660d6189
  name: ghcr.io/coendv/group1-notificationservice
  newName: ghcr.io/coendv/group1-notificationservice
- digest: sha256:9e374481f0bbd6dbbf7315f2575d618567b0757640a6db757769af873bb8898d
  name: ghcr.io/coendv/group1-recommendationservice
  newName: ghcr.io/coendv/group1-recommendationservice
- digest: sha256:50765966b0032e5cb13d2800c267889b98d99e53e352486ff9e0b5dd8753a33f
  name: ghcr.io/coendv/group1-userservice
  newName: ghcr.io/coendv/group1-userservice
- digest: sha256:943c5e90646b54adf6ba71b6e992e1dc179213efc8f62679d8c18d46b5a007c4
  name: ghcr.io/coendv/group1-videoservice
  newName: ghcr.io/coendv/group1-videoservice
