apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: projectgroup1-prod

resources:
- ../../base

images:
- name: ghcr.io/coendv/group1-chatservice
  newTag: main
- name: ghcr.io/coendv/group1-communityservice
  newTag: main
- name: ghcr.io/coendv/group1-notificationservice
  newTag: main
- name: ghcr.io/coendv/group1-recommendationservice
  newTag: main
- digest: sha256:e6dc928ff484cf350675f345356bfeae733a8e99a766f4eec77f8f56b630387c
  name: ghcr.io/coendv/group1-userservice
  newName: ghcr.io/coendv/group1-userservice
- digest: sha256:945e9e914e21e8905ec8790b3837504b3ad1644d80c7aa1e9bf936b1a1568cf9
  name: ghcr.io/coendv/group1-videoservice
  newName: ghcr.io/coendv/group1-videoservice
- digest: sha256:43a264cf1469e5180a616d5da2ea55ada864d579e265b3a842fc9a800081180d
  name: ghcr.io/inholland-cloud-minor-2526/group1-videoservice
  newName: ghcr.io/inholland-cloud-minor-2526/group1-videoservice
